import oracledb
import os
from dotenv import load_dotenv
import bcrypt
import requests
import datetime
from typing import Optional

load_dotenv()

# Credenciales Oracle desde .env
ORACLE_USER = os.getenv("ORACLE_USER")
ORACLE_PASSWORD = os.getenv("ORACLE_PASSWORD")
ORACLE_DSN = os.getenv("ORACLE_DSN")


class Database:
    def __init__(self, username, password, dsn):
        self.username = username
        self.password = password
        self.dsn = dsn

    def get_connection(self):
        return oracledb.connect(
            user=self.username,
            password=self.password,
            dsn=self.dsn
        )

    def create_all_tables(self):
        sql = """
        CREATE TABLE USERS (
            id NUMBER GENERATED BY DEFAULT AS IDENTITY,
            username VARCHAR2(50) UNIQUE NOT NULL,
            password RAW(60) NOT NULL,
            PRIMARY KEY (id)
        )
        """
        try:
            with self.get_connection() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(sql)
                connection.commit()
        except oracledb.DatabaseError:
            pass  # La tabla ya existe

    def query(self, sentence: str, parameters: Optional[dict] = None):
        try:
            with self.get_connection() as connection:
                with connection.cursor() as cursor:
                    cursor.execute(sentence, parameters or {})
                    if sentence.strip().upper().startswith("SELECT"):
                        return cursor.fetchall()
                    connection.commit()
        except oracledb.DatabaseError as error:
            print(f"Error en la query: {error}")
            return None


class Auth:

    @staticmethod
    def register(db: Database, username: str, password: str):
        salt = bcrypt.gensalt(12)
        hashed_password = bcrypt.hashpw(password.encode("utf-8"), salt)

        db.query(
            "INSERT INTO USERS(username, password) VALUES (:username, :password)",
            {
                "username": username,
                "password": hashed_password
            }
        )
        print("Usuario registrado correctamente")

    @staticmethod
    def login(db: Database, username: str, password: str) -> bool:
        resultado = db.query(
            "SELECT password FROM USERS WHERE username = :username",
            {"username": username}
        )

        if not resultado:
            return False

        password_db = resultado[0][0]
        return bcrypt.checkpw(password.encode("utf-8"), password_db)


class Finance:
    def __init__(self, base_url: str = "https://mindicador.cl/api"):
        self.base_url = base_url

    def _get_fecha(self, fecha: Optional[str]):
        if fecha:
            return fecha
        hoy = datetime.datetime.now()
        return f"{hoy.day}-{hoy.month}-{hoy.year}"

    def get_uf(self, fecha: str = None):
        fecha = self._get_fecha(fecha)
        url = f"{self.base_url}/uf/{fecha}"
        return requests.get(url).json()

    def get_ivp(self, fecha: str = None):
        fecha = self._get_fecha(fecha)
        url = f"{self.base_url}/ivp/{fecha}"
        return requests.get(url).json()

    def get_ipc(self, fecha: str = None):
        fecha = self._get_fecha(fecha)
        url = f"{self.base_url}/ipc/{fecha}"
        return requests.get(url).json()

    def get_utm(self, fecha: str = None):
        fecha = self._get_fecha(fecha)
        url = f"{self.base_url}/utm/{fecha}"
        return requests.get(url).json()

    def get_usd(self, fecha: str = None):
        fecha = self._get_fecha(fecha)
        url = f"{self.base_url}/dolar/{fecha}"
        return requests.get(url).json()

    def get_eur(self, fecha: str = None):
        fecha = self._get_fecha(fecha)
        url = f"{self.base_url}/euro/{fecha}"
        return requests.get(url).json()


if __name__ == "__main__":
    db = Database(ORACLE_USER, ORACLE_PASSWORD, ORACLE_DSN)
    db.create_all_tables()

    # Pruebas Auth
    Auth.register(db, "admin", "1234")
    login_ok = Auth.login(db, "admin", "1234")
    print("Login correcto:", login_ok)

    # Pruebas API
    finance = Finance()
    print(finance.get_uf())
